name: Build
on:
  workflow_dispatch:
  push:
    branches: [ master, portable ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install packages
        run: apk add mingw-w64-gcc make gcc musl-dev
      - name: Build busybox unicode
        run: |
          make mingw64u_defconfig
          make
      - name: Store busybox.exe
        uses: actions/upload-artifact@v3
        with:
          name: busybox
          path: busybox.exe